const assert = require('assert');
const fs = require('fs');

const src = fs.readFileSync('script.user.js', 'utf8');

function has(re, message) {
  assert(re.test(src), message);
}

function hasText(text, message) {
  assert(src.includes(text), message);
}

function notHas(re, message) {
  assert(!re.test(src), message);
}

// UPC registry integration
has(/@grant\s+GM_xmlhttpRequest/, 'Missing GM_xmlhttpRequest grant for UPC registry checks');
has(/@connect\s+unifiedpatentcourt\.org/, 'Missing @connect unifiedpatentcourt.org');
has(/function\s+refreshUpcRegistry\s*\(/, 'Missing UPC registry refresh function');
has(/function\s+upcCandidateNumbers\s*\(/, 'Missing UPC candidate-number selection helper');
has(/parseUpcOptOutResult/, 'Missing UPC opt-out parser');
hasText('IMPORTANT: UPC patent_number must be a publication number, never an EP application number.', 'UPC lookup should explicitly enforce publication-number-only input');
hasText('UPC registry check skipped: no EP publication numbers available', 'UPC lookup should skip cleanly when no EP publication numbers are available');
notHas(/if \(!picks\.length && \/^EP\\d\{6,\}\$\/i\.test\(caseNo \|\| ''\)/, 'UPC candidate selection should not fallback to application-number caseNo');
hasText("upcRegistry.status || (upcRegistry.optedOut ? 'Opted out' : 'No opt-out found')", 'Overview should preserve explicit UPC registry status (e.g., Opt-out withdrawn)');
hasText('opt(?:ed)?[\\s-]*out(?:\\s+\\w+){0,8}\\s+(?:register', 'UPC positive matcher should allow words between opt-out and registered/entered/effective');

// Timeline grouped items UX (collapsible + arrow)
has(/<details class="epoRP-grp" data-group-key=/, 'Timeline groups should render as keyed <details> containers');
has(/class="epoRP-garrow"/, 'Timeline group arrow indicator missing');
has(/\.epoRP-grp\[open\]\s+\.epoRP-garrow\{transform:rotate\(90deg\)/, 'Timeline arrow rotation style missing');
has(/timelineItemHtml\(item, compact = false, inGroup = false\)/, 'Timeline item renderer should support in-group styling');
has(/\.epoRP-it\.in-group\{/, 'Grouped timeline items should have dedicated styling hook');
has(/\.epoRP-grph::marker\{content:''\}/, 'Timeline group summary should hide default marker to avoid native grey button artefacts');
has(/function\s+timelineGroupKey\s*\(/, 'Timeline group key helper missing');
has(/data-group-key="\$\{esc\(groupKey\)\}"/, 'Timeline groups should render stable key attributes');
has(/function\s+persistLiveDoclistGroups\s*\(/, 'Doclist open-group persistence helper missing');
has(/function\s+timelineAttorneyImportance\s*\(/, 'Timeline importance classifier helper missing');
hasText('deemed to be withdrawn|application deemed to be withdrawn|loss of rights', 'Timeline importance classifier should escalate loss-of-rights events for attorney triage');
hasText('deadline|time limit|final date|summons to oral proceedings|rule\\s*116', 'Timeline importance classifier should mark prosecution-critical events as warn-level');
hasText("const defaultOpen = !!options().doclistGroupsExpandedByDefault;", 'Doclist grouping should derive default expand/collapse behaviour from a dedicated option');
hasText("const isOpen = hasSavedOpenState ? openGroups.has(groupKey) : defaultOpen;", 'Doclist grouping should respect the configured default expand/collapse state when there is no saved per-group state');
hasText("if (!hasSavedOpenState && defaultOpen) openGroups.add(groupKey);", 'Doclist auto-expanded state should only seed open groups when default-open behaviour is enabled');
hasText("if (key === 'doclistGroupsExpandedByDefault') clearDoclistOpenGroups(runtime.appNo || '');", 'Changing the doclist default-open toggle should clear saved per-case group state so refresh uses the new preference');
hasText("const sessionPersisted = loadSessionJson(`${OPTIONS_KEY}:session`, null);", 'Options loading should fall back to a session-storage copy when site-local persistence is flaky across refreshes');
hasText("saveSessionJson(`${OPTIONS_KEY}:session`, next);", 'Option writes should store a session backup so refresh keeps recent settings even if localStorage persistence is unreliable');
hasText('title=\"${esc(rightTitle)}\"', 'Top-right source badge should expose detailed per-source status on hover');
notHas(/persistLiveTimelineGroups\(/, 'Timeline open-state persistence should be removed so timeline groups start collapsed on each render');
has(/function\s+inferProceduralDeadlines\s*\(/, 'Deadline model should be derived by dedicated procedural deadline inference');
has(/function\s+addCalendarMonthsDetailed\s*\(/, 'Calendar-month calculation helper (with rollover detection) missing');
has(/function\s+timelineCacheKey\s*\(/, 'Timeline model should expose a cache key for memoization');
has(/@grant\s+unsafeWindow/, 'Userscript metadata should grant unsafeWindow for sandbox/page pdf.js bridging');
has(/const\s+PDF_JS_CANDIDATES\s*=\s*\[/, 'PDF parser should define multi-CDN loader candidates');
has(/const\s+OCR_TESSERACT_CANDIDATES\s*=\s*\[/, 'PDF OCR parser should define tesseract loader candidates');
has(/function\s+getUnsafeWindow\s*\(/, 'PDF parser should expose unsafeWindow bridge helper');
has(/function\s+getPdfJsGlobal\s*\(/, 'PDF parser should resolve pdf.js globals across sandbox/page scopes');
has(/function\s+clearInvalidNamedGlobals\s*\(/, 'PDF parser should clear stale library globals before retries');
has(/function\s+registerNamedGlobal\s*\(/, 'PDF parser should normalize discovered library globals back into known scopes');
has(/function\s+ensureNamedLibrary\s*\(/, 'External library loader helper missing');
has(/function\s+ensurePdfJs\s*\(/, 'PDF parser loader helper missing');
has(/function\s+ensureTesseract\s*\(/, 'PDF OCR parser loader helper missing');
has(/function\s+loadExternalScriptTag\s*\(/, 'PDF parser should support script-tag fallback loading');
has(/function\s+evaluateNamedLibraryCode\s*\(/, 'PDF parser should support multi-strategy library script evaluation fallback');
has(/function\s+refreshPdfDeadlines\s*\(/, 'PDF deadline refresh pipeline missing');
has(/async function extractPdfText\(url, signal, pdfjsInstance = null\)/, 'PDF extraction should accept preloaded pdf.js engine instance');
has(/async function extractTextFromPdfViaOcr\(binary, pdfjs, signal\)/, 'PDF extraction should include OCR fallback for image-only PDFs');
has(/function\s+isPdfBinaryData\s*\(/, 'PDF extraction should detect non-PDF payloads before parser invocation');
has(/function\s+binaryToUtf8\s*\(/, 'PDF extraction should decode binary payloads for HTML fallback parsing');
has(/function\s+hasMeaningfulCommunicationText\s*\(/, 'PDF extraction should score fallback HTML text quality before using it');
has(/function\s+focusCommunicationContextText\s*\(/, 'PDF extraction should focus fallback text around communication/deadline anchors');
has(/function\s+deriveDocumentPageUrlFromPdfUrl\s*\(/, 'PDF extraction should derive document-page URLs for empty-PDF fallback');
has(/function\s+extractPdfLikeUrlFromHtml\s*\(/, 'PDF extraction should probe HTML payloads for linked PDF/document URLs');
has(/function\s+pdfContentToStructuredText\s*\(/, 'PDF text extraction should include layout-aware line reconstruction helper');
has(/const\s+txt\s*=\s*pdfContentToStructuredText\(content\);/, 'PDF extraction should use structured line reconstruction per page');
has(/function\s+extractCommunicationDateFromPdf\s*\(/, 'PDF parser should extract communication date explicitly');
has(/function\s+extractResponseMonthsFromPdf\s*\(/, 'PDF parser should extract response-period month count from communication text');
has(/function\s+extractExplicitDeadlineDateFromPdf\s*\(/, 'PDF parser should support explicit deadline dates when present in the communication');
has(/function\s+inferDeadlineCategoryFromContext\s*\(/, 'PDF parser should infer category from document title/procedure metadata when text lacks legal markers');
hasText('Communication response period', 'PDF parser should support generic communication-category fallback for broader communication types');
has(/function\s+defaultResponseMonthsForCategory\s*\(/, 'PDF parser should provide conservative default response periods for key categories');
has(/function\s+extractRegisteredLetterProofLine\s*\(/, 'PDF parser should extract proof line below Registered Letter for logging');
hasText('registered\\s+letter\\b[:\\s\\-]*', 'Registered Letter parser should handle same-line payload patterns');
has(/function\s+normalizePdfDocumentUrl\s*\(/, 'PDF resolver should normalize javascript-based document links');
hasText('/^javascript:/i.test(raw)', 'PDF URL normalizer should detect javascript pseudo-links from doclist');
hasText('source.match(/\\/?application\\?documentId=', 'PDF URL normalizer should extract application?documentId links from javascript handlers');
hasText('/[?&]documentId=/i.test(normalized)', 'PDF resolver should allow direct EPO documentId endpoints without requiring .pdf suffix');
hasText('within\\s+(?:a\\s+)?(?:period|time\\s+limit)\\s+of\\s+([a-z]+|\\d{1,2})\\s+months?', 'PDF month parser should match "within a period of X months" wording');
has(/communicationDateStr\s*=\s*communication\.dateStr\s*\|\|\s*docDateStr/, 'PDF hint derivation should anchor to communication date with doclist fallback');
has(/addCalendarMonthsDetailed\(communicationDate,\s*responseMonths\)/, 'PDF month-based deadline should be computed from communication date + response period (explicit or fallback)');
hasText('PDF proof line (below "Registered Letter")', 'PDF parser logging should report line below Registered Letter to prove document was opened');
hasText('PDF parse diagnostics', 'PDF parser logging should emit communication-date/response-period diagnostics');
hasText('categoryEvidence', 'PDF parse diagnostics should expose whether category came from text or document metadata');
hasText('registeredLetterLine', 'PDF diagnostics should include captured Registered Letter line snippet');
hasText('registeredLetterProofLine', 'PDF diagnostics should include captured Registered Letter proof-line snippet');
hasText('Date extracted from Application/Ref/Date header table in PDF', 'Communication date extraction should prioritize central letter-header table date fields when available');
hasText('Date extracted from line below "Registered Letter" in PDF (dispatch proof context)', 'Communication date extraction should still capture Registered Letter proof-line date as lower-priority dispatch evidence');
hasText('Date extracted from EPO form stamp near Registered Letter (dispatch proof context)', 'Communication date extraction should keep EPO form stamp date cues as lower-priority dispatch evidence');
hasText('PDF communication date differs from doclist date (using PDF date for deadline derivation)', 'PDF diagnostics should flag and prefer PDF communication date when it differs from doclist date');
hasText('Default ${fallbackMonths}-month period inferred for ${category}', 'PDF parser should support conservative default response-period fallback when explicit month phrases are missing');
hasText('Derived from fragmented phrase', 'PDF parser should detect fragmented month phrase patterns such as "of 4 months"');
hasText('(?:2|3|5|6|two|three|five|six)', 'PDF parser should include explicit fragmented target month detection for 2/3/5/6 month phrases');
hasText('Derived from fragmented target phrase', 'PDF parser should log targeted fragmented month phrase evidence when matched');
hasText('Derived from reversed fragmented target phrase', 'PDF parser should detect reversed fragmented month phrase ordering');
hasText('PDF binary unavailable; using HTML fallback text extraction', 'PDF parser should log explicit HTML fallback path when binary response is not a valid PDF');
hasText('pdfjs-via-linked-url-empty-text', 'PDF parser should expose explicit transport tag when linked PDF has no extractable text layer');
hasText('html-fallback-from-document-page-after-empty-linked-pdf-text', 'PDF parser should support fallback from document-page HTML after empty linked-PDF text extraction');
hasText('normalizedDocUrl', 'PDF URL failure logging should include normalized URL attempt for debugging');
hasText('PDF parser engine ready', 'PDF parser should log successful engine initialization before scanning documents');
hasText('PDF OCR fallback used', 'PDF parser should explicitly log when OCR extraction path is used for image-only PDFs');
hasText('PDF parser unavailable:', 'PDF parser should log explicit engine-loader failures');
hasText('PDF deadline parse aborted (parser engine unavailable)', 'PDF parser should stop clearly when engine is unavailable');
has(/extractPdfText\(resolvedUrl,\s*signal,\s*pdfjs\)/, 'PDF parse loop should reuse a preloaded pdf.js engine instance');
hasText('PDF deadline scan skipped: no communication-type documents found', 'PDF scan should report explicit skip when no communication-type docs are eligible');
has(/\)\.slice\(0,\s*8\);/, 'PDF communication candidate selection should cover broader communication set (top 8 docs)');
has(/parsePdfDeadlineHints\(text,\s*\{[\s\S]*docTitle:\s*doc\.title,[\s\S]*docProcedure:\s*doc\.procedure,[\s\S]*\}\)/, 'PDF hint parsing should receive document metadata context for category fallback');
has(/const\s+resolvedByActivity\s*=\s*resolveHintByActivity\(label,\s*anchor\);/, 'PDF-derived deadlines should be re-checked against subsequent activity to mark older cycles resolved');
hasText('resolved by subsequent activity', 'PDF-derived deadline method text should indicate when a deadline cycle has already been resolved');
has(/withProofLine:\s*scanned\.filter\(/, 'PDF summary logging should include proof-line hit count');
has(/withResponsePeriod:\s*scanned\.filter\(/, 'PDF summary logging should include response-period hit count');
has(/withOcr:\s*scanned\.filter\(/, 'PDF summary logging should include OCR-path usage count');
has(/function\s+sourceDiagnostics\s*\(/, 'Source diagnostics helper should summarize parsed feature payloads');
hasText("const parseMessage = classified.status === 'ok'", 'Fetch parse logging should classify ok vs empty/notFound outcomes before logging');
has(/addLog\(caseNo,\s*parseLevel,\s*parseMessage,[\s\S]*sourceDiagnostics\(src\.key,\s*parsed\)/, 'Fetch parse logs should include feature-level source diagnostics for classified source states');
has(/addLog\(caseNo,\s*parseLevel,\s*parseMessage,[\s\S]*sourceDiagnostics\(sourceKey,\s*data\)/, 'Live parse logs should include feature-level source diagnostics for classified source states');
hasText('const logs = (getCase(caseNo).logs || []).slice(-MAX_LOGS_PER_APP).reverse();', 'Operation console should render latest logs first');
hasText('autoPrefetchDoneByCase', 'Init should track per-case auto-prefetch completion in current page session');
hasText('lastRegisterTabByCase', 'Init should track previous register tab per case to detect same-case tab switches');
hasText('SESSION_KEY', 'Init gate should persist page-session state in sessionStorage');
hasText('getCaseSession(caseNo)', 'Init should load case session state before applying prefetch gate');
hasText('patchCaseSession(caseNo, { prefetchDoneAt: gateTs, lastRegisterTab: registerTab });', 'Init should persist prefetch gate state to session storage for reload-safe same-tab switching');
hasText('Initial case load: stale/missing sources detected; running auto prefetch', 'Init should log initial auto-prefetch decisions');
hasText('Prefetch gate bypassed: stale/missing sources detected', 'Init should bypass session gate when stale/missing sources are detected');
hasText('staleSources', 'Prefetch logs should include stale source-key diagnostics');
hasText('Case tab/page changed; auto prefetch skipped for this page session', 'Init should skip repeated auto-prefetch on case/page switches in this session');
hasText('Same-case tab switch detected: prefetch gate active', 'Init should log explicit same-case tab switch gate decisions');
hasText('Same-case page reload detected: prefetch gate active', 'Init should log explicit same-case reload gate decisions');
hasText('Initial case load: cache is fresh; no auto prefetch needed', 'Init should log fresh-cache reuse on first case load');
has(/const\s+tabChangedWithinCase\s*=\s*hasPreviousTab\s*&&\s*previousRegisterTab\s*!==\s*registerTab;/, 'Init should detect same-case tab changes for gate logging across reloads');
notHas(/addEventListener\('focus',[\s\S]*prefetchCase\(/, 'Focus handler should not auto-reload all sources after same-case tab/page changes');
has(/inferProceduralDeadlines\(main,\s*docs,\s*eventHistory,\s*legal,\s*pdfDeadlines\)/, 'Overview deadline model should include PDF-derived hints');

// Timeline controls (include/exclude + importance)
has(/const\s+OPTION_DEFS\s*=\s*\[/, 'Options should be defined from a shared schema');
has(/key:\s*'showEventHistory'[\s\S]*id:\s*'epoRP-opt-events'/, 'Timeline event include toggle missing from option schema');
has(/key:\s*'showLegalStatusRows'[\s\S]*id:\s*'epoRP-opt-legal'/, 'Timeline legal include toggle missing from option schema');
has(/key:\s*'timelineEventLevel'[\s\S]*id:\s*'epoRP-opt-event-level'/, 'Timeline event level selector missing from option schema');
has(/key:\s*'timelineLegalLevel'[\s\S]*id:\s*'epoRP-opt-legal-level'/, 'Timeline legal level selector missing from option schema');

// Options diagnostics console + effective key/value snapshot
has(/function\s+renderLogConsole\s*\(caseNo\)/, 'Operation console renderer missing');
has(/function\s+formatLogClock\s*\(/, 'Operation console should include timestamp formatter helper');
has(/function\s+safeInlineJson\s*\(/, 'Operation console should include safe JSON serializer helper');
has(/function\s+optionValueText\s*\(/, 'Option snapshot should include value-normalization helper');
has(/function\s+renderOptions\s*\(caseNo\)/, 'Options renderer should accept caseNo to scope diagnostics to current case');
has(/function\s+renderOptionControl\s*\(/, 'Options renderer should build controls from the shared schema');
has(/function\s+renderOptionSection\s*\(/, 'Options renderer should build sections from the shared schema');
has(/id="epoRP-log-console"/, 'Operation console container missing from options view');
has(/id="epoRP-clear-logs"/, 'Clear operation console button missing from options view');
has(/function\s+renderOptionSnapshot\s*\(/, 'Option snapshot renderer missing');
has(/function\s+optionSnapshotKeys\s*\(/, 'Option snapshot should centralize key ordering');
has(/extraKeys\s*=\s*Object\.keys\(optionState\)\.filter\(/, 'Option snapshot should keep unknown option keys visible and sorted after known ones');
has(/id="epoRP-optvals"/, 'Option key/value list container missing from options view');
has(/renderOptionSnapshot\(\)/, 'Options view should render option key/value snapshot output');
has(/renderLogConsole\(caseNo\)/, 'Options view should render operation console scoped to current case');
has(/b\.querySelector\('#epoRP-clear-logs'\)\?\.addEventListener\('click',\s*\(\)\s*=>\s*\{[\s\S]*?c\.logs\s*=\s*\[\];[\s\S]*?rerenderPanelPreservingCurrentScroll\(\);[\s\S]*?\}\);/, 'Clear operation console control should empty case logs and rerender options without losing sidebar scroll');
has(/function\s+commitOptionValue\s*\(/, 'Option changes should flow through a shared commit helper');
hasText('Current option values', 'Options view should show a section listing effective option values');
hasText('Expand doclist groups by default', 'Options view should expose a dedicated default expand/collapse toggle for doclist packet groups');
hasText('class="epoRP-optsec"', 'Options view should organize settings into visually separated categories');

// Publications parsing + tab readability improvements
has(/function\s+normalizePublicationNumber\s*\(/, 'Publication-number normalization helper missing');
has(/function\s+splitPublicationNumber\s*\(/, 'Publication number/kind splitter helper missing');
has(/const\s+publicationField\s*=\s*publicationSections\.join\('\\n'\)\s*\|\|\s*fieldByLabel\(doc,\s*\[\/\^Publication\\b\/i\]\);/, 'Main parser should match Publication* label variants including multi-row publication sections');
has(/const\s+reDateBeforeNumber\s*=\s*new RegExp/, 'Publication parser should support date-before-number layouts');
hasText('(?:EP|WO|US|JP|CN|KR|DE|FR|GB|CA|AU|BR|IN)', 'Publication parser should include broad publication-country prefixes');
has(/\.epoRP-tab\.on\{background:#bfdbfe;color:#0f172a;border-color:#93c5fd/, 'Selected tab styling should use dark text for readability');

// UI removals requested
notHas(/Document index/, 'Document index UI should be removed');
notHas(/data-view="logs"/, 'Logs tab should be removed');
notHas(/IPC\/CPC/, 'IPC/CPC should be removed from UI');

// Data-cleaning and case typing regressions
has(/dedupeMultiline/, 'dedupeMultiline helper missing');
has(/parentCase/, 'Divisional parent case tracking missing');
has(/cleanTitle/, 'Title cleanup helper missing');
notHas(/isDivisional:\s*!!parentCase\s*\|\|\s*priorities\.some\(\(p\)\s*=>\s*\/\^EP\/i\.test\(p\.no\)\)/, 'Divisional detection should not rely on EP priority numbers alone');
has(/function\s+extractEpNumbersByHeader\s*\(/, 'Header-based EP number extraction helper missing');
has(/extractEpNumbersByHeader\(doc,\s*\/\\bParent application/, 'Parent application extraction should use header-scoped helper');
has(/extractEpNumbersByHeader\(doc,\s*\/\\bDivisional application/, 'Divisional child extraction should use header-scoped helper');
hasText('[A-Z]{2}\\d[0-9A-Z\\/\\-]{4,}', 'Priority parser should require numeric body after country code (prevents LANGUAGE false matches)');
hasText('Filing language|Procedural language|Publication|Applicant|Representative|Status|Most recent event', 'Priority page-text fallback should stop at known next labels to avoid pulling publication rows');
hasText('priority document|annex', 'Annex filings should be classed with the filing package when applicant-filed');
hasText('Response to search', 'Search-response applicant bundle should exist for grouped amendments after search report');
hasText('isGrantContext', 'Document classifier should detect intention-to-grant / text-proposed-for-grant context');
hasText('isGrantResponse', 'Document classifier should detect applicant responses to intention-to-grant context');
has(/isSearchResponseContext && !isGrantContext/, 'Search-response grouping should not swallow intention-to-grant responses');
has(/return \{ bundle: 'Grant package', level: 'warn', actor: 'Applicant' \};/, 'Intention-to-grant responses should be grouped with grant package context');
has(/annex to \(\?:the \)\?communication\|communication annex\|annex\.\*examining division/, 'Annex-to-communication should be classed as EPO examination material');
has(/const\s+internationalField\s*=\s*dedupeMultiline\(fieldByLabel\(doc,\s*\[\/\^International application\\b\/i,\s*\/\^International publication\\b\/i,\s*\/\^PCT application\\b\/i\]\)\);/, 'E/PCT detection should use international-application scoped fields');
notHas(/const\s+isEuroPct\s*=\s*!!internationalAppNo\s*\|\|\s*\/\\bPCT\\b\/i/, 'E/PCT detection should not rely on broad page-wide PCT token matching');
has(/function\s+enhanceDoclistGrouping\s*\(/, 'All-documents grouping enhancer missing');
has(/epoRP-docgrp/, 'All-documents grouping row class missing');
has(/headerRow\.classList\.toggle\('open',\s*nextExpanded\)/, 'All-documents group header should mark expanded state for styling');
has(/epoRP-docgrp-open/, 'All-documents grouped rows should get expanded-state class for background differentiation');
has(/function\s+getDoclistOpenGroups\s*\(/, 'All-documents open-state persistence helper missing');
has(/epoRP-docgrp-check/, 'All-documents group header should include a select-all checkbox');
notHas(/>Select<|>All</, 'All-documents group header should keep the checkbox-only control without extra header text');
hasText('epoRP-docgrp-meta', 'All-documents group header should render item-count/page-total metadata');
hasText('doclistGroupSummaryHtml(run)', 'All-documents group header should render centralized item-count/page-total summary text');
has(/dispatchEvent\(new Event\('change',\s*\{ bubbles: true \}\)\)/, 'Group select-all should emit row checkbox change events');
has(/epoRP-docgrp-item\.epoRP-docgrp-last\.epoRP-docgrp-open td\{border-bottom:2px solid #bfdbfe\}/, 'All-documents grouped rows should draw a bottom boundary line when expanded');
has(/appearance:none\s*!important;-webkit-appearance:none\s*!important/, 'All-documents group header control should suppress native button chrome');
has(/function\s+epRenewalDueDate\s*\(/, 'Renewal model should compute EP due dates from filing-anniversary month');
has(/feeForum\s*=\s*'EPO central \(Unitary Patent\)'/, 'Renewal model should distinguish UP central-fee forum');
has(/graceUntil\s*=\s*nextDue\s*\?\s*addMonths\(nextDue,\s*6\)\s*:\s*null;/, 'Renewal model should include 6-month grace-period calculation');
hasText("const graceText = m.renewal.graceUntil", 'Renewals overview should still derive grace-period text inline inside the next-due row');
hasText("terminalPosture ? 'Historical grace until' : 'Grace until'", 'Renewals overview should soften grace-period wording on terminal cases while keeping it in the next-due row');
hasText('Last payment', 'Renewals overview should surface latest renewal inside the compact status row');
notHas(/<div class="epoRP-l">Latest renewal<\/div>/, 'Renewals overview should not render a separate Latest renewal row');
notHas(/<div class="epoRP-l">Grace period until<\/div>/, 'Renewals overview should not render a separate Grace period row');
has(/return 'Post-publication';/, 'Stage mapping should avoid using "Published" as a stage label');
has(/return 'Closed';/, 'Stage mapping should classify withdrawn/refused/revoked outcomes as Closed');
has(/const\s+detailedDeadlines\s*=\s*m\.deadlines\.filter\(/, 'Overview should compute detailed deadlines separately from the active next deadline summary');
hasText('Detailed clocks', 'Overview should embed detailed/reference clocks inside actionable status');
notHas(/Deadlines & clocks \(detailed\)/, 'Overview should no longer render a separate Deadlines & clocks section');
hasText('Type / stage', 'Overview should combine type and stage in a single summary row');
has(/const\s+termReference\s*=\s*m\.deadlines\.find\(/, 'Overview should compute 20-year term reference from deadline model');
has(/const\s+filingSummary\s*=\s*normalize\(\[/, 'Overview should build a condensed filing summary line');
hasText("termReferenceDate ? `20-year term ${termReferenceDate}` : ''", 'Overview filing summary should include the 20-year term reference inline without extra years-remaining noise');
notHas(/<div class="epoRP-l">20-year term from filing \(reference\)<\/div>/, 'Overview should not render a separate 20-year term row after condensing filing metadata');
has(/if \(d\.reference && \/20-year term from filing\/i\.test\(String\(d\.label \|\| ''\)\)\) return false;/, 'Detailed clocks should avoid duplicating 20-year term reference row already shown in top summary');
has(/if \(d\.resolved \|\| d\.superseded\) return false;/, 'Detailed clocks should hide deadlines already resolved or superseded by later activity/outcomes');
has(/<div class="epoRP-l">Latest actions<\/div>/, 'Actionable status should combine EPO and applicant activity into one row');
has(/<div class="epoRP-l">Waiting on<\/div>/, 'Actionable status should render waiting-party summary row');
hasText('Loss-of-rights posture detected.', 'Actionable status should expose concise recovery guidance for loss-of-rights postures');
has(/const\s+latestEpoIsLossOfRights\s*=\s*\/deemed to be withdrawn\|application deemed to be withdrawn\|loss of rights/, 'Overview model should detect loss-of-rights posture from latest EPO action');
has(/const\s+waitingOn\s*=\s*latestEpoIsLossOfRights/, 'Waiting-on allocation should use dedicated loss-of-rights logic');
has(/const\s+nextDeadlineMetaLines\s*=\s*\[\];/, 'Actionable status should build tidy next-deadline metadata lines');
hasText('Basis: ${nextDeadlineMethod}', 'Actionable status should render method evidence as a dedicated Basis line');
notHas(/nextDeadlineMeta\s*=\s*m\.nextDeadline/, 'Legacy one-line next-deadline metadata blob should be removed');
hasText('since applicant response', 'Waiting-on summary should include elapsed applicant-response time when applicable');
notHas(/<div class="epoRP-l">EPO last action<\/div>/, 'Actionable status should not render a separate EPO last action row after consolidation');
notHas(/<div class="epoRP-l">Applicant last filing<\/div>/, 'Actionable status should not render a separate applicant last filing row after consolidation');
notHas(/<div class="epoRP-l">Days since applicant response<\/div>/, 'Actionable status should not render a separate day-counter row after consolidation');
has(/const\s+liveTable\s*=\s*bestTable\(document,\s*\['date',\s*'document'\]\)\s*\|\|\s*bestTable\(document,\s*\['document type'\]\)/, 'Doclist filter should resolve current table on each input (avoid stale table reference)');
hasText('const fallbackCaseNo = runtime.fetchCaseNo || runtime.appNo || detectAppNo();', 'Doclist parser should use a safe fallback case number for sourceUrl generation');
hasText("sourceUrl(fallbackCaseNo, 'doclist')", 'Doclist parser should avoid undefined caseNo when generating fallback doclist URLs');
hasText('Intention to grant (R71(3) EPC)', 'Doclist group label should use explicit R71(3) wording for grant package groups');
hasText('Response to intention to grant', 'Doclist grouping should expose a dedicated label for applicant responses to R71(3) packets');
hasText('Transfer / recordal filings', 'Doclist/timeline grouping should expose a more specific register-admin label for transfer/recordal packets');
hasText('Art. 94(3) communication', 'Timeline/doc labels should be able to upgrade examination packet names from OCR/PDF-derived Art. 94(3) evidence');
hasText('No unitary effect record', 'UPC / UE presentation should avoid echoing overall withdrawn status as if it were a unitary-effect record');
hasText('Loss-of-rights communication', 'Timeline/detail labeling should upgrade generic examination-row wording for terminal-loss-of-rights documents');
hasText('historical central-fee date', 'Renewals overview should soften overdue central-fee wording on terminal/withdrawn cases');
hasText('Historical grace until', 'Renewals overview should soften grace-period wording on terminal/withdrawn cases');
hasText('Examination communication', 'Doclist grouping should expose a dedicated label for Art. 94(3)/examining-division communication packets');
hasText('Response to examination communication', 'Doclist grouping should expose a dedicated label for applicant responses to examining-division communications');
hasText('tr.epoRP-docgrp td:first-child{box-shadow:inset 3px 0 0 #3b82f6}', 'Doclist group header should show a strong blue left guide line');
hasText('tr.epoRP-docgrp-item.epoRP-docgrp-open td:first-child{box-shadow:inset 3px 0 0 #93c5fd}', 'Doclist grouped child rows should show a lighter blue continuation guide line');
has(/if \(sameDateGrantSignals\) model\.bundle = 'Grant package';/, 'Doclist grouping should fold same-date bibliographic rows into intention-to-grant group when grant signals are present');
has(/const\s+runKey\s*=\s*`\$\{kind\}\|\$\{model\.dateStr \|\| ''\}`;/, 'Doclist grouping runs should be anchored to date as well as group kind so repeated cycles do not merge across dates');
has(/if \(hasGrantResponse && \(model\.signals\.isGrantResponseExplicit \|\| model\.signals\.isReceipt \|\| \(model\.actor === 'Applicant' && model\.signals\.isResponseCompanion\)\)\)/, 'Doclist grouping should promote same-date applicant companion filings and receipts into grant-response packets when explicit grant-response rows are present');
has(/if \(hasExamResponse && \(model\.signals\.isExamResponseExplicit \|\| model\.signals\.isReceipt \|\| \(model\.actor === 'Applicant' && model\.signals\.isResponseCompanion\)\)\)/, 'Doclist grouping should promote same-date applicant companion filings and receipts into examination-response packets when explicit examination-response rows are present');
has(/const\s+isLossOfRights\s*=\s*\/deemed to be withdrawn\|application deemed to be withdrawn\|loss of rights/, 'Document classification should mark loss-of-rights communications as EPO actions');
has(/function\s+doclistGroupingSignature\s*\(/, 'Doclist grouping should compute a structural signature for change detection');
has(/runtime\.doclistGroupSigByCase\[caseNo\]\s*===\s*signature/, 'Doclist grouping should skip full regroup when table signature is unchanged');
hasText('items.push(...timelineDocItemsFromDocs(caseNo, docs, pdfDeadlines));', 'Timeline should reuse the shared doclist packet-grouping model instead of keeping a stale parallel bundling path');
hasText('const nextDeadline = selectNextDeadline(deadlines, latestEpoIsLossOfRights);', 'Overview should suppress stale overdue clocks on closed/loss-of-rights postures via centralized next-deadline selection');
hasText('const nextDeadlineNote = activeDeadlineNoteText(deadlines, latestEpoIsLossOfRights);', 'Overview should surface explanatory text when no active deadline remains after supersession');
hasText('upcUe: upcUePresentationModel(ue, upcRegistry, federated),', 'Overview should derive UPC / UE wording through the centralized presentation model');
hasText('timelineSubtitleText(item)', 'Timeline item rendering should dedupe subtitle labels through the centralized formatter');
hasText('const detail = normalize(e.detail || \'\');', 'Event/legal timeline items should stop embedding their source labels inside detail text now that subtitle rendering handles source separately');
hasText('const terminalPosture = /closed|withdrawn|refused|revoked/i.test', 'Renewals overview should detect terminal case posture before choosing overdue vs historical wording');
hasText("actor && actor !== 'Other' ? actor : ''", 'Timeline subtitle rendering should omit the generic actor=Other suffix when it adds no value');
hasText('shouldAppendSingleRunLabel(item.detail, groupLabel)', 'Single-item document rows should skip broad run labels like Examination/Other when a stronger upgraded label already exists');
has(/if \(runtime\.activeView !== 'timeline'\) renderPanel\(\);/, 'Focus/visibility refresh should avoid unnecessary timeline rerendering');
has(/function\s+panelScrollKey\s*\(/, 'Panel scroll key helper missing');
hasText("if (url.searchParams.has('documentId')) return false;", 'Case-page detection should skip document-viewer URLs');
hasText('return /^EP\\d+/i.test(appNoFromUrl(url));', 'Case-page detection should require EP application number in URL query (number=...)');
has(/function\s+persistCurrentPanelScroll\s*\(/, 'Panel scroll persistence helper missing');
has(/restorePanelScroll\(caseNo,\s*activeView,\s*scrollRestoreOverride\)/, 'Panel scroll should be restored after rerender with same-view scroll preservation');
has(/function\s+panelScrollRestoreOverride\s*\(/, 'Panel scroll same-view override helper missing');
has(/nextDeadlineBadge/, 'Actionable status should show next-deadline day delta inline');
hasText('rolled over', 'Deadline metadata should include rollover indicator when applicable');
notHas(/<div class="epoRP-l">Most recent event<\/div>/, 'Actionable status should not render a separate Most recent event row');
has(/el\.addEventListener\('input',\s*commit\)/, 'Options toggles should react on input events for reliable checkbox commits');

console.log('userscript regression checks passed');
